#!/usr/bin/env python
"""Regenerate api/index.py with public/index.html embedded as base64.

Vercel's static-file serving and `functions.includeFiles` both proved unreliable
for this project, so the read-only function carries the page inline. Re-run this
whenever you edit the frontend:

    python build_function.py
"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
html = (ROOT / "public" / "index.html").read_text()
b64 = base64.b64encode(html.encode()).decode()

TEMPLATE = '''"""Read-only API + page server for Vercel (GENERATED by build_function.py).

Imports NO heavy dependencies (no pandas/yfinance) so the serverless bundle stays
small. The dashboard HTML is embedded below; data comes from the cloud KV store.
Edit public/index.html and re-run build_function.py to regenerate this file.
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from fastapi import FastAPI, Request                         # noqa: E402
from fastapi.responses import HTMLResponse, JSONResponse    # noqa: E402

from app import store                                        # noqa: E402
from app.agent_view import augment_agents_view, augment_equity_curves  # noqa: E402

app = FastAPI(title="Terravue (read-only)")

_HTML = base64.b64decode("__B64__").decode()


@app.get("/api/status")
def status():
    sugg = store.read_json("suggestions") or {}
    return {
        "llm_enabled": bool(sugg.get("narrative_source") == "claude"),
        "read_only": True,
        "universe_size": len(sugg.get("suggestions", [])),
    }


@app.get("/api/suggestions")
def suggestions():
    return store.read_json("suggestions") or {
        "date": None, "narrative": "No analysis published yet. Run the daily job.",
        "narrative_source": "rules", "suggestions": [],
    }


@app.get("/api/agents")
def agents(live: bool = False):
    view = augment_agents_view(store.read_json("agents_view"))
    if live:
        from app import live as live_view, stockinfo
        tickers = [
            h["ticker"]
            for a in view.get("agents", [])
            for h in a.get("snapshot", {}).get("holdings", [])
        ]
        view = live_view.revalue_agents_view(view, stockinfo.get_live_prices(tickers))
    return view


@app.get("/api/stock/{ticker}")
def stock(ticker: str, intraday: bool = False):
    from app import stockinfo
    av = store.read_json("agents_view")
    pre = store.read_json("sd:" + ticker.upper().strip())
    if pre:
        if intraday or not (pre.get("series") or {}).get("intraday_1d"):
            live = stockinfo.get_stock_detail(ticker, av, force_intraday=intraday)
            for key in ("intraday_1d", "intraday_5d"):
                if (live.get("series") or {}).get(key):
                    pre.setdefault("series", {})[key] = live["series"][key]
            for key in ("price", "chg_1d"):
                if live.get(key) is not None:
                    pre[key] = live[key]
        pre["holders"] = stockinfo._holders_for(ticker.upper().strip(), av)
        return pre
    return stockinfo.get_stock_detail(ticker, av, force_intraday=intraday)


@app.get("/api/equity-history")
def equity_history():
    return augment_equity_curves(store.read_json("equity_curves"))


@app.get("/api/news")
def news():
    return store.read_json("news_feed") or {"reactions": [], "headlines": []}


@app.post("/api/chat")
async def chat(request: Request):
    from app import chat as stock_chat
    body = await request.json()
    suggestions = store.read_json("suggestions") or {"suggestions": []}
    agents_view = augment_agents_view(store.read_json("agents_view"))
    news_feed = store.read_json("news_feed") or {"reactions": [], "headlines": []}
    return stock_chat.answer(body.get("message", ""), suggestions, agents_view, news_feed)


@app.post("/api/run-agent")
def run_agent():
    return JSONResponse(
        {"error": "read_only",
         "message": "This is a read-only deployment. The agent runs automatically "
                    "after each market close and publishes results here."},
        status_code=503,
    )


@app.get("/")
def home():
    return HTMLResponse(_HTML)


@app.get("/{path:path}")
def spa(path: str):
    return HTMLResponse(_HTML)
'''

out = ROOT / "api" / "index.py"
out.write_text(TEMPLATE.replace("__B64__", b64))
print(f"Wrote {out} with embedded page ({len(b64)} b64 chars from "
      f"{len(html)} bytes of HTML).")
